### PR TITLE
[FEATURE] Go 1.10 release add to TravisCI

### PR DESCRIPTION
**Pull request by im-kulikov**
- add go 1.10 release
- rem go 1.7 release

### CODE REVIEW

**Comment by bgaifullin** [comment]
Please squash commits.

**Comment by im-kulikov** [comment]
@bgaifullin ok, one moment

**Comment by im-kulikov** [comment]
@bgaifullin fixed, and tests passed
___
build 80 - mailru dbr - travis ci 2018-02-25 23-36-30

**Comment by bgaifullin** [comment]
Thank you.

**Pull request merged**
